/* 🤖 this file was generated by svg-to-ts */

import { WuiIconModel } from './build/wui-icon.model';

export type WuiIconModelNameSubset<
  T extends Readonly<WuiIconModel[]>
> = T[number]['name'];

export * from './build/-bluetooth.icon';
export * from './build/-calendar-bold.icon';
export * from './build/-calendar.icon';
export * from './build/-camera-bold.icon';
export * from './build/-camera.icon';
export * from './build/-filter-bold.icon';
export * from './build/-filter.icon';
export * from './build/-folder.icon';
export * from './build/-keyboard-arrow-next.icon';
export * from './build/-zip-file.icon';
export * from './build/wui-icon.model';
