/* 🤖 this file was generated by svg-to-ts */

export type WuiIconName =
  | 'bluetooth'
  | 'calendarBold'
  | 'calendar'
  | 'cameraBold'
  | 'camera'
  | 'filterBold'
  | 'filter'
  | 'folder'
  | 'keyboardArrowNext'
  | 'zipFile';
export interface WuiIconModel {
  name: WuiIconName;
  data: string;
}
